Repository seL4/seL4_tools, pull requests merged in 2021-09, with the labels that each got.

#103 Pass a1 as received from OpenSBI to main's second argument
  elfloader-tool/src/arch-riscv/crt0.S
Labels: bug

#113 elfloader: cleanup defines
  elfloader-tool/include/binaries/efi/efi.h
  elfloader-tool/include/types.h
  elfloader-tool/src/string.c
Labels: cleanup

#117 elfloader/risc-v: improve OpenSBI support
  cmake-tool/helpers/rootserver.cmake
Labels: enhancement

#122 elfloader/risc-v: improve comments
  elfloader-tool/src/arch-riscv/crt0.S
Labels: cleanup

#123 elfloader/risc-v: inline spi_probe_extension
  elfloader-tool/src/arch-riscv/crt0.S
Labels: cleanup
