Repository seL4/seL4_tools, pull requests merged in 2022-02, with the labels that each got.

#137 github: enable hw-test and hw-build on PRs
  .github/workflows/sel4test-hw.yml
Labels: CI

#136 elfloader,RISC-V: Fix early boot issues
  elfloader-tool/src/arch-riscv/crt0.S
Labels: bug, hw-test

#140 elfloader/risc-v: minor SBI wrapper code cleanup
  elfloader-tool/include/arch-riscv/sbi.h
Labels: cleanup
